// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt2ZV1BASN-N6zADXc_DvTnC8SJbyD2ow',
    appId: '1:640944653867:web:d66931fe1a68b5b461cc6e',
    messagingSenderId: '640944653867',
    projectId: 'chatdemo-e899d',
    authDomain: 'chatdemo-e899d.firebaseapp.com',
    storageBucket: 'chatdemo-e899d.appspot.com',
    measurementId: 'G-1ZJPEF3FK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSbYdoHFfmm4_P8qqDXLugwdhgT_F5St0',
    appId: '1:640944653867:android:e3be6e678b604d6461cc6e',
    messagingSenderId: '640944653867',
    projectId: 'chatdemo-e899d',
    storageBucket: 'chatdemo-e899d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXiMaJ5YKKDogWkaabSw-hM_rWuK5Ge0U',
    appId: '1:640944653867:ios:6bc54da0bd2d0e2561cc6e',
    messagingSenderId: '640944653867',
    projectId: 'chatdemo-e899d',
    storageBucket: 'chatdemo-e899d.appspot.com',
    iosClientId: '640944653867-8k6nt3apfsfo98cjubanp89d3ugrjatj.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneWord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXiMaJ5YKKDogWkaabSw-hM_rWuK5Ge0U',
    appId: '1:640944653867:ios:6bc54da0bd2d0e2561cc6e',
    messagingSenderId: '640944653867',
    projectId: 'chatdemo-e899d',
    storageBucket: 'chatdemo-e899d.appspot.com',
    iosClientId: '640944653867-8k6nt3apfsfo98cjubanp89d3ugrjatj.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneWord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt2ZV1BASN-N6zADXc_DvTnC8SJbyD2ow',
    appId: '1:640944653867:web:64a61e4ee746679061cc6e',
    messagingSenderId: '640944653867',
    projectId: 'chatdemo-e899d',
    authDomain: 'chatdemo-e899d.firebaseapp.com',
    storageBucket: 'chatdemo-e899d.appspot.com',
    measurementId: 'G-KMJB963HS2',
  );
}
